name: C/C++ CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  path: ./bgfx
            - uses: actions/checkout@v1
              with:
                  path: ./bx
                  repository: bkaradzic/bx
                  ref: refs/heads/master
            - uses: actions/checkout@v1
              with:
                  path: ./bimg
                  repository: bkaradzic/bimg
                  ref: refs/heads/master
            # TODO: cache this dependency.
            - name: Install build dependencies.
              run: sudo apt-get install mesa-common-dev libglu1-mesa-dev
            - name: Generate project files.
              run: make
            - name: Compile.
              run: make linux-release64
