name: C/C++ CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  path: ./bgfx
            - uses: actions/checkout@v1
              with:
                  path: ./bx
                  repository: bkaradzic/bx
                  ref: refs/heads/master
            - uses: actions/checkout@v1
              with:
                  path: ./bimg
                  repository: bkaradzic/bimg
                  ref: refs/heads/master
            - name: generate project files
              run: make
              working-directory: ./bgfx
            - name: make
              run: make linux-release64
              working-directory: ./bgfx
